version: '3.8'

services:
  db_v2:
    image: postgres:15
    container_name: postgres-db-v2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: meu_banco
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
    - my_network

volumes:
  postgres_data_v2:
    driver: local

networks:
  my_network:
    external: true